project_id = "atfrjhydmhpdwfepbkij"

[functions.process-scheduled-broadcasts]
verify_jwt = false

[functions.notify-login]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.notify-revision]
verify_jwt = false

[functions.notify-article-status]
verify_jwt = false

[functions.notify-unauthorized-access]
verify_jwt = false

[functions.notify-new-registration]
verify_jwt = false
