project_id = "atfrjhydmhpdwfepbkij"

[functions.process-scheduled-broadcasts]
verify_jwt = false

[functions.notify-login]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.notify-revision]
verify_jwt = false

[functions.notify-article-status]
verify_jwt = false

[functions.notify-unauthorized-access]
verify_jwt = false

[functions.notify-new-registration]
verify_jwt = false

[functions.admin-auth-login]
verify_jwt = false

[functions.notify-registration-status]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-reminder-incomplete]
verify_jwt = false

[functions.notify-selection-stage]
verify_jwt = false

[functions.notify-first-login]
verify_jwt = false
